In [33]:
import os
def cal_result(exp_name, criterion='best', verbose=False, draw_cm=False):
    import dill as pickle
    data_stream = 70
    week_n = 7000 
    cnt = 0
    tp = 0
    fp = 0
    sum_a = 0
    sum_n = 0
    AVG = {'tpr':0.0,'fpr':0.0, 'AUC' :0.0} 

    with open('data/y.pkl', 'rb') as f:
        y = pickle.load(f).flatten().tolist()

    for stream in range(36, data_stream + 1): 
        pre = (stream - 1) * 7000
        
        flag = False 
        start, end = pre + week_n, pre + 2 * week_n
        for j in range(start, end): 
            if y[j] == 1: 
                flag = True; sum_a += 1 
            else: sum_n += 1

        def read_score(exp_name, week): 
            lst = []
            exp_name = os.path.join(os.path.join("exp2", exp_name), exp_name)
            with open(exp_name + "Week" + str(week) +  "_result.txt", "r") as f: 
                sc = float(f.readline()) 
                while sc != None: 
                    lst.append(sc)

                    s = f.readline()
                    # while !s: s = f.readline()
                    if s == '': break  
                    sc = float(s) 

            return lst                

        if flag : 
            cnt += 1
            x_score = read_score(exp_name, stream)
            from sklearn.metrics import roc_curve, auc
            GT = y[start: end]
            from sklearn.metrics import roc_auc_score
            AUC = roc_auc_score(GT, x_score)
            if verbose:  print(stream, " week :", AUC)  #*
            
            # print(len(x_score), GT) 
            FPR, TPR, thresholds = roc_curve(GT, x_score)
            maxindex = (TPR-FPR).tolist().index(max(TPR-FPR))
            threshold = thresholds[maxindex]
            tpr, fpr = TPR[maxindex], FPR[maxindex]
            if verbose: print("tpr: %f , fpr: %f, thresh: %f\n" % (tpr, fpr, threshold)) #*

            tp += sum([1 if x >= threshold and y == 1 else 0 for x, y in zip(x_score, GT)])
            fp += sum([1 if x >= threshold and y == 0 else 0 for x, y in zip(x_score, GT)])
            for i in AVG.keys(): 
                AVG[i] += eval(i)
            # if criterion == 'bset': 
                # JD = [x - y for x, y in zip(TPR, FPR)]
    # for i in AVG.keys():
    #      AVG[i] /= cnt
    print(tp, sum_a, fp, sum_n)
    fn = sum_a - tp; tn = sum_n - fp 
    if draw_cm: 
        import matplotlib.pyplot as plt
        import numpy as np
        from sklearn.metrics import confusion_matrix
        from sklearn.metrics import ConfusionMatrixDisplay
        cm = np.array([[tn, fp], [fn, tp]])
        print(cm)
        ig = plt.figure()
        plt.matshow(cm)
        plt.title('Confusion Matrix')
        plt.colorbar()
        plt.ylabel('True Label')
        plt.xlabel('Predicated Label')
        for first_index in range(len(cm)):
            for second_index in range(len(cm[first_index])):
                plt.text(first_index, second_index, cm.T[first_index][second_index])
        plt.savefig('confusion_matrix' + exp_name +'.jpg')

        plt.close('all')
    return {'tpr':tp / sum_a,'fpr': fp / sum_n, "TP":tp , "FN":fn, "FP": fp, "TN": tn}

# cal_result("exp_icarl_NN_0")


In [34]:
def f(p):
    import pandas as pd 
    flag = False
    df = None
    # p = ["exp_naive_"]

    for i in range(0, 5): 
        tmp = cal_result(p[0] + str(i), verbose=False,draw_cm=False) # draw_cm: 是否可视化 
        if flag != False: df = pd.concat([df, pd.DataFrame(data=tmp, index=[0])], axis=0) 
        else : df = pd.DataFrame(data=tmp, index=[0]); flag = True
    return df

# display(df)
# df.describe()
# pd.DataFrame(data=df.describe().loc['mean', :].to_dict(), index=[0])

In [35]:
idx = [('FineTune', 'exp_finetune_' ),("icarl","exp_icarl_"),("icarl with NN","exp_icarl_NN_"),('随机初始化AE',"exp_randominit_"),("随机输出分数", "exp_randomoutput_"), ("非0特征数作为分数", "exp_naive_")]

In [36]:
y = [f([idx[i][1]]) for i in range(0, 6)]
import pandas as pd 
tmp = [pd.DataFrame(data=x.describe().loc['mean', :].to_dict(), index=[0]) for x in y ]
d = pd.concat(tmp, axis=0)

512 583 58154 244417
[[186263  58154]
 [    71    512]]
506 583 56168 244417
[[188249  56168]
 [    77    506]]
511 583 58946 244417
[[185471  58946]
 [    72    511]]
510 583 57922 244417
[[186495  57922]
 [    73    510]]
498 583 57540 244417
[[186877  57540]
 [    85    498]]
490 583 57064 244417
[[187353  57064]
 [    93    490]]
494 583 51922 244417
[[192495  51922]
 [    89    494]]
517 583 61120 244417
[[183297  61120]
 [    66    517]]
493 583 60142 244417
[[184275  60142]
 [    90    493]]
489 583 56454 244417
[[187963  56454]
 [    94    489]]
547 583 32059 244417
[[212358  32059]
 [    36    547]]
549 583 30065 244417
[[214352  30065]
 [    34    549]]
531 583 29642 244417
[[214775  29642]
 [    52    531]]
545 583 32279 244417
[[212138  32279]
 [    38    545]]
538 583 32216 244417
[[212201  32216]
 [    45    538]]
500 583 47419 244417
[[196998  47419]
 [    83    500]]
500 583 50491 244417
[[193926  50491]
 [    83    500]]
504 583 51583 244417
[[192834  51583]
 [    79  

In [37]:
d.index = list(list(zip(*idx))[0])

# p = d.style.set_properties(**{'text-align': 'left'})
d

tpr       fpr     TP     FN        FP        TN
FineTune       0.870326  0.236260  507.4   75.6   57746.0  186671.0
icarl          0.851801  0.234601  496.6   86.4   57340.4  187076.6
icarl with NN  0.929674  0.127864  542.0   41.0   31252.2  213164.8
随机初始化AE        0.859005  0.208587  500.8   82.2   50982.2  193434.8
随机输出分数         0.607204  0.438369  354.0  229.0  107144.8  137272.2
非0特征数作为分数      0.888508  0.162280  518.0   65.0   39664.0  204753.0

In [38]:
import pandas as pd 
flag = False
df = None
p = ["exp_finetune_0", "exp_icarl_0", "exp_icarl_NN_0"]


for i in p: 
    j = i
    tmp = cal_result(j, verbose=False) 
    print(tmp)
    if flag != False: df = pd.concat([df, pd.DataFrame(data=tmp, index=[0])], axis=0) 
    else : df = pd.DataFrame(data=tmp, index=[0]); flag = True

df.describe().loc['mean', :].to_dict()


512 583 58154 244417
{'tpr': 0.8782161234991424, 'fpr': 0.23792944025988372, 'TP': 512, 'FN': 71, 'FP': 58154, 'TN': 186263}
490 583 57064 244417
{'tpr': 0.8404802744425386, 'fpr': 0.2334698486602814, 'TP': 490, 'FN': 93, 'FP': 57064, 'TN': 187353}
547 583 32059 244417
{'tpr': 0.9382504288164666, 'fpr': 0.1311651808180282, 'TP': 547, 'FN': 36, 'FP': 32059, 'TN': 212358}


{'tpr': 0.885648942252716,
 'fpr': 0.20085482324606443,
 'TP': 516.3333333333334,
 'FN': 66.66666666666667,
 'FP': 49092.333333333336,
 'TN': 195324.66666666666}